// src/components/react/counter.tsx
import { useState } from "react"

export const Counter = () => {
  const [count, setCount] = useState(0)

  return (
    <>
      <h1>React Counter</h1>
      <button onClick={() => setCount(count - 1)}>Decrement</button>
      <span>Count: {count}</span>
      <button onClick={() => setCount(count + 1)}>Increment</button>
    </>
  )
}

// src/components/vue/counter.vue
<script setup lang="ts">
import { ref } from "vue"
const counter = ref(0)
const increment = () => {
  counter.value++
}
const decrement = () => counter.value--
</script>

<template>
  <h1>Vue Counter</h1>
  <button @click="decrement">Decrement</button>
  <span>Count: {{ counter }}</span>
  <button @click="increment">Increment</button>
</template>
